/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ForgeRouteImport } from './routes/forge'
import { Route as GuildRouteImport } from './routes/guild'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as RealmRouteImport } from './routes/realm'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as BlocksIndexRouteImport } from './routes/blocks/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeRoute = ForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildRoute = GuildRouteImport.update({
  id: '/guild',
  path: '/guild',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RealmRoute = RealmRouteImport.update({
  id: '/realm',
  path: '/realm',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksIndexRoute = BlocksIndexRouteImport.update({
  id: '/blocks/',
  path: '/blocks/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/forge': typeof ForgeRoute
  '/guild': typeof GuildRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/policy': typeof PolicyRoute
  '/realm': typeof RealmRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/blocks/': typeof BlocksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/forge': typeof ForgeRoute
  '/guild': typeof GuildRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/policy': typeof PolicyRoute
  '/realm': typeof RealmRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/blocks': typeof BlocksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/forge': typeof ForgeRoute
  '/guild': typeof GuildRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/policy': typeof PolicyRoute
  '/realm': typeof RealmRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/blocks/': typeof BlocksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/explore'
    | '/forge'
    | '/guild'
    | '/jobs'
    | '/login'
    | '/policy'
    | '/realm'
    | '/shop'
    | '/signup'
    | '/blocks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/explore'
    | '/forge'
    | '/guild'
    | '/jobs'
    | '/login'
    | '/policy'
    | '/realm'
    | '/shop'
    | '/signup'
    | '/blocks'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/explore'
    | '/forge'
    | '/guild'
    | '/jobs'
    | '/login'
    | '/policy'
    | '/realm'
    | '/shop'
    | '/signup'
    | '/blocks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ExploreRoute: typeof ExploreRoute
  ForgeRoute: typeof ForgeRoute
  GuildRoute: typeof GuildRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  PolicyRoute: typeof PolicyRoute
  RealmRoute: typeof RealmRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  BlocksIndexRoute: typeof BlocksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge': {
      id: '/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof ForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guild': {
      id: '/guild'
      path: '/guild'
      fullPath: '/guild'
      preLoaderRoute: typeof GuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realm': {
      id: '/realm'
      path: '/realm'
      fullPath: '/realm'
      preLoaderRoute: typeof RealmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/': {
      id: '/blocks/'
      path: '/blocks'
      fullPath: '/blocks/'
      preLoaderRoute: typeof BlocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ExploreRoute: ExploreRoute,
  ForgeRoute: ForgeRoute,
  GuildRoute: GuildRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  PolicyRoute: PolicyRoute,
  RealmRoute: RealmRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  BlocksIndexRoute: BlocksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
